services:
  hr-ops-portal-frontend-dev:
    container_name: hr-ops-portal-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CI=true
    command: ["sh", "-c", "pnpm install && pnpm dev --host"]
    networks:
      - hr-ops-portal-network

networks:
  hr-ops-portal-network:
    external: true
